package request;

public class LoginRequest {
    //DATA MEMBERS
    /**
     * Unique user name that serves as an identifier
     */
    String username;
    /**
     * Pass code generated by user
     */
    String password;

    //CONSTRUCTOR
    /**
     * Object needed to log in
     * @param username Unique user name that serves as an identifier
     * @param password Pass code generated by user
     */
    public LoginRequest(String username, String password){
        this.username = username;
        this.password = password;
    }

    //SETTERS AND GETTERS
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}
